spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled:true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  jmx:
    enabled:true
  data:
    rest:
      base-path: sdr
  messages:
    encoding: UTF-8

management:
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "caches-cache"
      base-path: "/metrics"
  health:
    diskspace:
      enabled: true
    defaults:
      enabled: true

logging:
  level:
    ROOT: DEBUG
  file:
    name: "hw16"