spring:
  datasource:
    url: jdbc:h2:mem:maindb
  liquibase:
    enabled:true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  cache:
    cache-names:
      - security/acl
logging:
  level:
    org:
      springframework:
        security: TRACE